# Web Vulnerability Laboratory
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop-lab
    ports:
      - "3000:3000"
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge